name: Releaser
on:
  pull_request_target:
    types: [ labeled, closed ]
  issue_comment:
    types: [ created, edited ]

jobs:
  pr_merged:
    runs-on: ubuntu-latest
    name: Trigger job on comment, merge or label
    steps:
      - name: Trigger release
        id: release
        uses: RedHatInsights/frontend-releaser@v1
        with:
          bot-name: nacho-bot
          gh-bot-token: ${{ secrets.GH_BOT_TOKEN }}
          travis-config: '{"token":"${{ secrets.TRAVIS_TOKEN }}", "script": "npm run release:bot"}'
